shaker/urls.py
from django.urls import path
from . import views


app_name = 'shaker'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DrinksView.as_view(), name='drinks'),
    path('add/', views.AddDrinkView.as_view(), name='add'),
    path('list_drinks/', views.ListDrinksView.as_view(), name='list_drinks'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('search/', views.SearchView.as_view(), name='search'),
]

zonedrinks/urls.py
import document as document
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shaker.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shaker/models.py
from django.db import models


alcoholType = (
    (1, 'Vodka'),
    (2, 'Whisky'),
    (3, 'Gin'),
    (4, 'Tequila'),
    (5, 'Rum'),
    (6, 'Rakija'),
)


class Drinks(models.Model):
    name_drink = models.CharField(max_length=100)
    desc_drink = models.CharField(max_length=100)
    alcohol_type = models.IntegerField(choices=alcoholType)
    image_drink = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name_drink


class Ingredients(models.Model):
    drinks = models.ForeignKey(Drinks, on_delete=models.CASCADE)
    name_ingredient = models.CharField(max_length=100)

    def __str__(self):
        return self.name_ingredient

shaker/forms.py
from django import forms
from .models import Drinks, Ingredients, alcoholType


class DrinksForm(forms.Form):
    name_drink = forms.CharField(label='Name drink')
    desc_drink = forms.CharField(label='Short desc')
    alcohol_type = forms.ChoiceField(choices=alcoholType)
    pub_date = forms.DateTimeField(label='Date public', widget=forms.SelectDateWidget)


class IngredientForm(forms.Form):
    name_ingredient = forms.CharField(label='Name Ingredient')


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password_conf = forms.CharField(label="Password confirmation", widget=forms.PasswordInput)
    email = forms.EmailField(label="Email")


class SearchForm(forms.Form):
    name_drink = forms.CharField(max_length=100, label="Search...", required=False)

shaker/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic, View

from .forms import DrinksForm, IngredientForm, LoginForm, RegistrationForm, SearchForm
from .models import Drinks, Ingredients


class IndexView(View):

    def get(self, request):
        drinks_list = Drinks.objects.all()
        context = {
            'drinks_list': drinks_list,
        }
        return render(request, 'shaker/index.html', context)


class ListDrinksView(View):

    def get(self, request):
        drinks_list = Drinks.objects.all()
        context = {
            'drinks_list': drinks_list,
        }
        return render(request, 'shaker/list_drinks.html', context)


class AddDrinkView(LoginRequiredMixin, View):

    def get(self, request):
        form = DrinksForm()
        context = {
            'form': form
        }
        return render(request, 'shaker/add.html', context)

    def post(self, request):
        form = DrinksForm(request.POST)
        if form.is_valid():
            Drinks.objects.create(
                name_drink=form.cleaned_data['name_drink'],
                desc_drink=form.cleaned_data['desc_drink'],
                alcohol_type=form.cleaned_data['alcohol_type'],
            )

        else:
            messages.error(request, 'Ops, we have a problem.')

        return HttpResponseRedirect(reverse('shaker:index'))


class DrinksView(View):

    def get(self, request, pk):
        form_ingredient = IngredientForm
        ingredient_list = Ingredients.objects.filter(drinks=pk)
        try:
            drinks = Drinks.objects.get(pk=pk)
        except Drinks.DoesNotExist:
            raise Http404("Drink does not exist")
        context = {
            'drinks': drinks,
            'form_ingredient': form_ingredient,
            'ingredient_list': ingredient_list,
        }
        # print(ingredient_list)
        return render(request, 'shaker/drinks.html', context)

    def post(self, request, pk):
        drinks = get_object_or_404(Drinks, pk=pk)
        form_ingredient = IngredientForm(request.POST)
        if form_ingredient.is_valid():
            Ingredients.objects.create(
                drinks=drinks,
                name_ingredient=form_ingredient.cleaned_data["name_ingredient"]
            )
        return HttpResponseRedirect(reverse('shaker:drinks', args=(drinks.id,)))


class LoginView(View):

    def get(self, request):
        form = LoginForm()
        context = {
            'form': form
        }
        return render(request, 'shaker/login.html', context)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                url = request.GET.get('next')
                if url:
                    return redirect(url)
                return HttpResponseRedirect(reverse('shaker:index'))
            messages.error(request, 'Username or password invalid')
            return HttpResponseRedirect(reverse('shaker:login'))
        messages.error(request, 'Form was not valid')
        return HttpResponseRedirect(reverse('shaker:login'))


class LogoutView(LoginRequiredMixin, View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('shaker:login'))


class RegistrationView(View):

    def get(self, request):
        form = RegistrationForm()
        context = {
            "form": form
        }
        return render(request, 'shaker/registration.html', context)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["password"] == form.cleaned_data["password_conf"]:
                try:
                    User.objects.get(username=form.cleaned_data["username"])
                    messages.error(request, "User already exists")
                    return HttpResponseRedirect(reverse("polls:registration"))
                except User.DoesNotExist:
                    user = User.objects.create_user(
                        username=form.cleaned_data["username"],
                        password=form.cleaned_data["password"],
                        email=form.cleaned_data["email"]
                    )
                    login(request, user)
                    return HttpResponseRedirect(reverse("shaker:index"))
            else:
                messages.error(request, "Passwords are wrong!")
                return HttpResponseRedirect(reverse("shaker:registration"))


class SearchView(View):

    def get(self, request):
        form = SearchForm()
        context = {
            'form': form
        }
        return render(request, 'shaker/search.html', context)

    def post(self, request):
        form = SearchForm(request.POST)
        results = None
        if form.is_valid():
            results = Drinks.objects.filter(
                name_drink__contains=form.cleaned_data['name_drink']
            )
        context = {
            'form': form,
            'results': results
        }
        return render(request, 'shaker/search.html', context)

shaker/templates/shaker/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Drink</title>
</head>
<body>

<h3>Add Drink</h3>

<form action="{% url 'shaker:add'%}" method="post">
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Add">
</form>

<a href="{% url 'shaker:index' %}">Home</a>

</body>
</html>

shaker/templates/shaker/drinks.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Drinks</title>
</head>

<body>

<h1>{{ drinks.name_drink }}</h1>

{% for ingredient in ingredient_list %}

{{ ingredient.name_ingredient }}<br>

{% endfor %}

<h3>Add Ingredient</h3>
<form action="{% url 'shaker:drinks' drinks.id %}" method="post">
  {% csrf_token %}

  {{ form_ingredient.as_p }}

  <input type="submit" value="Send">

</form>

</body>

</html>

shaker/templates/shaker/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
<!--    <link rel="stylesheet" type="text/css" href="{% static 'shaker/style.css' %}">-->
    <title>Index</title>
</head>
<body>
{% if messages %}
<h2>{{ message }}</h2>
{% endif %}

{% if user.is_authenticated %}
{{ user }}
<a href="{% url 'shaker:logout' %}">Logout</a>
{% else %}
Please, <a href="{% url 'shaker:login' %}">login</a> or <a href="{% url 'shaker:registration' %}">create account</a>.
{% endif %}

<h1>Welcome to database drinks</h1>

{% if drinks_list %}
  <ul>
    {% for drinks in drinks_list %}
      <li><a href="{% url 'shaker:drinks' drinks.id %}"> {{ drinks.name_drink }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>no drinks are available</p>
{% endif %}

<a href="{% url 'shaker:search' %}">Search Drink</a><br>

<a href="{% url 'shaker:add' %}">Add drink</a><br>
<a href="{% url 'shaker:list_drinks' %}">List Drinks</a><br>

</form>

</body>
</html>

shaker/templates/shaker/list_drinks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista drinków</title>

    <style>
        ul {
        list-style-type: none;
        }
    </style>

</head>
<body>

{% if drinks_list %}
  <ul>
    {% for drinks in drinks_list %}
      <li><a href="{% url 'shaker:drinks' drinks.id %}">{{ drinks.name_drink }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>no drinks are available</p>
{% endif %}

</body>
</html>

shaker/templates/shaker/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

{% if messages %}
{% for message in messages %}
<h2>{{ message }}</h2>
{% endfor %}
{% endif %}

<h2>Login</h2>

<form action="{% url 'shaker:login' %}" method="post">
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Login">
</form>

<a href="{% url 'shaker:registration' %}">Registration</a>

</body>
</html>

shaker/templates/shaker/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>

<h2>Registration</h2>

<form action="{% url 'shaker:registration' %}" method="post">
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Create account">
</form>

</body>
</html>

shaker/templates/shaker/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>

<h2>Search drinks</h2>

<form action="{% url 'shaker:search' %}" method="post">
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Search">
</form>

{% if results %}
{% for drinks in results %}
<li><a href="{% url 'shaker:drinks' drinks.id %}"> {{ drinks.name_drink }}</a></li>
{% endfor %}
{% else %}
No drinks in the list.
{% endif %}

<a href="{% url 'shaker:index' %}">Home</a>

</body>
</html>